baseURL = "https://jiufengblog.web.app/"
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
languageCode = "en-us"
title = "Feng"
theme = "lightbi-hugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
#pygmentsUseClasses = true
#pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"
enableRobotsTXT = true
enableGitInfo = false

summaryLength  = "30"

[pagination]
pagerSize = 6

[Params]
selfHosted = true
mainSections = ["blogs"]
dateFormat = "02 January 2006"
comments = false
readingTime = true
wordCount = true
useHLJS = true
socialShare = true
delayDisqus = true
showRelatedPosts = true
summaryLength  = "9"
lunrSearch = true
gcse = false
lastmod = true
rss = false
pagination = "9"
hideAuthor = false
description="Your can add your website description here."
previewCardImagePlacement = "bottom"
since = "2024"
website = "https://jiufengblog.web.app/"



[Params.Author]
  name = "Jiufeng Li"
  website = "https://jiufengblog.web.app/"
  authorInfo = "Build yourself and believe in yourself."
  authorPostImage = "/img/author/author_bottom.jpg"
    email = "lijiufeng97@gmail.com"
  facebook = "username"
  instagram = "jiufeng.li"
  youtube = "user/username" # or channel/channelname
  twitter = "username"
  linkedin = "jiufeng"
  github = "username"
  threads = "username"
  gitlab = "username"
  reddit = "username"
  stackoverflow = "users/XXXXXXX/username"
  snapchat = "username"
  spotify = "username"
  paypal = "username"
  telegram = "username"
  mastodon = "url"
  slack = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #500px = "username"
  #kaggle = "username"
  #weibo = "username"
  #xing = "username"
  #bitbucket = "username"
  #soundcloud = "username"
  # codepen = "username"

  

#Menu configuration 
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1


[[menu.main]]
    name = "Blogs"
    url = "/blogs/"
    weight = 2

[[menu.main]]
    name = "Collections"
    url = "/collections/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
